// Copyright 2026 RelyChan Pte. Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authmode

import (
	"bytes"
	"fmt"
	"net"
	"slices"
	"strings"

	"github.com/hasura/goenvconf"
	"github.com/invopop/jsonschema"
	"github.com/relychan/gohttps/middlewares"
	"github.com/relychan/goutils"
)

// ClientIPLocation represents the location where the client IP should be parsed from.
type ClientIPLocation uint8

const (
	// ClientIPFromXForwardedFor represents the location of client IP read from the X-Forwarded-For header,
	// walking the chain right-to-left and skipping any IP that falls within one of the given trusted CIDR prefixes.
	// The first IP that is not trusted is the client.
	// ClientIPFromXForwardForTrustedProxies stores the client IP read from the X-Forwarded-For header, given the exact number of trusted reverse proxies between this server and the public internet.
	// It returns the IP at position len(xff) - numTrustedProxies in the merged X-Forwarded-For list — the IP added by the outermost of your trusted proxies,
	// the only IP in the chain that none of your proxies have allowed an attacker to forge.
	ClientIPFromXForwardedFor ClientIPLocation = iota
	// ClientIPFromHeader stores the client IP from a single-IP header set by your reverse proxy.
	// Only safe with headers your proxy unconditionally OVERWRITES on every request, e.g.:  X-Real-IP, X-Client-IP, CF-Connecting-IP.
	// If the header reaches us with multiple values (misconfigured proxy that appends, or a downstream proxy not stripping a client-supplied value),
	// the LAST value wins — that's the one set by the hop closest to us, and therefore the most trusted.
	// Fail-closed if the last value doesn't parse: no client IP is set rather than falling back to earlier (less-trusted) values.
	// v4-mapped IPv6 (::ffff:a.b.c.d) folds to plain v4 and IPv6 zones are stripped before storage.
	ClientIPFromHeader
	// ClientIPFromRemoteAddr stores the client IP read from the TCP RemoteAddr of the incoming request — the IP address of whoever opened the connection to this server.
	// Use this strategy when this server is directly connected to the public internet with NO reverse proxy in front of it.
	// Behind a reverse proxy, RemoteAddr is the proxy's IP, not the client's — use ClientIPFromHeader or ClientIPFromXFF instead.
	// IPv4 clients on a dual-stack listener surface as ::ffff:a.b.c.d; they fold to plain v4 before storage so one logical client maps to one key.
	// IPv6 zones are preserved (link-local connections may legitimately have one).
	ClientIPFromRemoteAddr
)

var enumValueClientIPLocation = []string{
	string(middlewares.ClientIPFromXForwardedFor),
	string(middlewares.ClientIPFromHeader),
	string(middlewares.ClientIPFromRemoteAddr),
}

// IsValid if the current instance is valid.
func (j ClientIPLocation) IsValid() bool {
	return j < 3
}

// String implements fmt.Stringer interface.
func (j ClientIPLocation) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValueClientIPLocation[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j ClientIPLocation) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *ClientIPLocation) UnmarshalText(text []byte) error {
	result, err := ParseClientIPLocation(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j ClientIPLocation) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *ClientIPLocation) UnmarshalJSON(input []byte) error {
	value := bytes.Trim(input, `"`)

	return j.UnmarshalText(value)
}

// JSONSchema defines a custom definition for JSON schema.
func (ClientIPLocation) JSONSchema() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "string",
		Description: "The position of the IP to select. Default is the X-Forwarded-For header.",
		Enum:        goutils.ToAnySlice(GetClientIPLocations()),
		Default:     ClientIPFromXForwardedFor.String(),
	}
}

// ParseClientIPLocation parses a [ClientIPLocation] from string.
func ParseClientIPLocation(value string) (ClientIPLocation, error) {
	switch middlewares.ClientIPResolutionType(value) {
	case middlewares.ClientIPFromRemoteAddr:
		return ClientIPFromRemoteAddr, nil
	case middlewares.ClientIPFromHeader:
		return ClientIPFromHeader, nil
	case middlewares.ClientIPFromXForwardedFor:
		return ClientIPFromXForwardedFor, nil
	default:
		return 255, fmt.Errorf(
			"%w, got: %s",
			ErrInvalidClientIPLocation,
			value,
		)
	}
}

// GetClientIPLocations get the list of forwarded IP position enum.
func GetClientIPLocations() []string {
	return enumValueClientIPLocation
}

// RelyAuthIPAllowList holds security rules of the IP allow list from the parsed config.
type RelyAuthIPAllowList struct {
	goutils.ValidateIPOptions

	Headers                []string
	Location               ClientIPLocation
	TrustedProxyIPPrefixes []*net.IPNet
	NumTrustedProxies      int32
}

// AllowedIPsFromConfig creates a [RelyAuthIPAllowList] instance from config.
func AllowedIPsFromConfig(
	conf *RelyAuthIPAllowListConfig,
	getEnvFunc goenvconf.GetEnvFunc,
) (*RelyAuthIPAllowList, error) {
	if conf == nil ||
		((conf.Include == nil || conf.Include.IsZero()) && (conf.Exclude == nil || conf.Exclude.IsZero())) {
		return nil, ErrEmptyAllowedIPs
	}

	if getEnvFunc == nil {
		getEnvFunc = goenvconf.GetOSEnv
	}

	include, err := parseEnvSubnets(conf.Include, getEnvFunc)
	if err != nil {
		return nil, fmt.Errorf("failed to parse allowed IP: %w", err)
	}

	exclude, err := parseEnvSubnets(conf.Exclude, getEnvFunc)
	if err != nil {
		return nil, fmt.Errorf("failed to parse disallowed IP: %w", err)
	}

	location := conf.Location
	if !conf.Location.IsValid() {
		return nil, ErrInvalidClientIPLocation
	}

	result := &RelyAuthIPAllowList{
		ValidateIPOptions: goutils.ValidateIPOptions{
			AllowedIPRanges: include,
			BlockedIPRanges: exclude,
			PublicIPOnly:    conf.PublicOnly,
		},
		Location:          location,
		NumTrustedProxies: conf.NumTrustedProxies,
	}

	switch location {
	case ClientIPFromHeader:
		if len(conf.Headers) == 0 {
			return nil, ErrClientIPHeaderRequired
		}

		headers := make([]string, 0, len(conf.Headers))

		for _, header := range conf.Headers {
			if header == "" {
				continue
			}

			headers = append(headers, strings.ToLower(header))
		}

		slices.Sort(headers)

		result.Headers = slices.Compact(headers)
	case ClientIPFromXForwardedFor:
		if len(conf.TrustedProxyIPPrefixes) > 0 {
			result.TrustedProxyIPPrefixes = make([]*net.IPNet, 0, len(conf.TrustedProxyIPPrefixes))

			for _, prefix := range conf.TrustedProxyIPPrefixes {
				prefix = strings.TrimSpace(prefix)
				if prefix == "" {
					continue
				}

				subnet, err := goutils.ParseSubnet(prefix)
				if err != nil {
					return nil, err
				}

				result.TrustedProxyIPPrefixes = append(result.TrustedProxyIPPrefixes, subnet)
			}
		}
	default:
	}

	return result, nil
}

// Validate checks if the request satisfies the security rule.
func (rai *RelyAuthIPAllowList) Validate(body *AuthenticateRequestData) error {
	clientIP, err := rai.GetClientIPs(body)
	if err != nil {
		return err
	}

	return goutils.ValidateIP(clientIP, rai.ValidateIPOptions)
}

// GetClientIPs gets the client IPs from request data.
func (rai *RelyAuthIPAllowList) GetClientIPs(data *AuthenticateRequestData) (net.IP, error) {
	if data == nil || len(data.Headers) == 0 {
		return nil, ErrIPNotFound
	}

	switch rai.Location {
	case ClientIPFromHeader:
		for _, name := range rai.Headers {
			ip := parseHeaderAddr(data.Headers[name])
			if ip != nil {
				return ip, nil
			}
		}

		return nil, ErrInvalidIP
	case ClientIPFromXForwardedFor:
		return rai.parseXFFAddr(data.Headers["x-forwarded-for"])
	default:
		remoteAddr := data.RemoteAddr
		if remoteAddr == "" {
			return nil, ErrIPNotFound
		}

		host, _, err := net.SplitHostPort(remoteAddr)
		if err != nil {
			host = remoteAddr // RemoteAddr may already be a bare IP (e.g. in tests).
		}

		ip := parseHeaderAddr(host)
		if ip == nil {
			return nil, ErrInvalidIP
		}

		return ip, nil
	}
}

func (rai *RelyAuthIPAllowList) parseXFFAddr(value string) (net.IP, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil, ErrIPNotFound
	}

	if rai.NumTrustedProxies < 1 && len(rai.TrustedProxyIPPrefixes) == 0 {
		return parseHeaderAddr(value), nil
	}

	rawIPs := strings.Split(value, ",")

	if rai.NumTrustedProxies > 0 && len(rawIPs) != int(rai.NumTrustedProxies) {
		return nil, fmt.Errorf(
			"%w; expected %d trusted proxies, got %d",
			ErrInvalidIP, rai.NumTrustedProxies, len(rawIPs),
		)
	}

	if len(rai.TrustedProxyIPPrefixes) > 0 {
		err := rai.validateXFFTrustedProxyIPPrefixes(rawIPs)
		if err != nil {
			return nil, err
		}
	}

	ip := parseHeaderAddr(rawIPs[0])
	if ip == nil {
		return nil, ErrInvalidIP
	}

	return ip, nil
}

func (rai *RelyAuthIPAllowList) validateXFFTrustedProxyIPPrefixes(rawIPs []string) error {
	for pi := len(rawIPs) - 1; pi > 0; pi-- {
		rawIP := strings.TrimSpace(rawIPs[pi])
		if rawIP == "" {
			return fmt.Errorf("%w; proxy IP is empty", ErrInvalidIP)
		}

		proxyIP := net.ParseIP(rawIP)
		if proxyIP == nil {
			return fmt.Errorf("%w; invalid proxy IP %s", ErrInvalidIP, rawIP)
		}

		if !inAnyIPPrefix(proxyIP, rai.TrustedProxyIPPrefixes) {
			return fmt.Errorf(
				"%w; proxy IP %s is not in %s prefixes",
				ErrInvalidIP, rawIP, rai.printTrustedProxyIPPrefixes(),
			)
		}
	}

	return nil
}

func (rai *RelyAuthIPAllowList) printTrustedProxyIPPrefixes() string {
	var sb strings.Builder

	sb.Grow(20 * len(rai.TrustedProxyIPPrefixes))
	sb.WriteByte('[')

	for i, prefix := range rai.TrustedProxyIPPrefixes {
		if i > 0 {
			sb.WriteString(", ")
		}

		sb.WriteString(prefix.String())
	}

	sb.WriteByte(']')

	return sb.String()
}

func parseHeaderAddr(value string) net.IP {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}

	commaIndex := strings.IndexRune(value, ',')
	if commaIndex == -1 {
		return net.ParseIP(value)
	}

	part := strings.TrimSpace(value[:commaIndex])
	if part == "" {
		return nil
	}

	return net.ParseIP(value)
}

// inAnyIPPrefix reports whether ip falls within any of the given prefixes.
func inAnyIPPrefix(ip net.IP, prefixes []*net.IPNet) bool {
	for _, p := range prefixes {
		if p.Contains(ip) {
			return true
		}
	}

	return false
}
