// Copyright 2026 RelyChan Pte. Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authmode

import (
	"bytes"
	"fmt"
	"net"
	"slices"
	"strings"

	"github.com/hasura/goenvconf"
	"github.com/relychan/goutils"
	"github.com/relychan/jsonschema"
)

// ForwardedIPPosition represents the position of the IP to select from X-Forwarded-For header.
type ForwardedIPPosition uint8

const (
	// IPPositionRightmost presents the rightmost position.
	IPPositionRightmost ForwardedIPPosition = iota
	// IPPositionLeftmost presents the leftmost position.
	IPPositionLeftmost
	// IPPositionEdge presents the edge position.
	IPPositionEdge
)

var enumValueForwardedIPPositions = []string{
	"rightmost",
	"leftmost",
	"edge",
}

// IsValid if the current instance is valid.
func (j ForwardedIPPosition) IsValid() bool {
	return j < 3
}

// String implements fmt.Stringer interface.
func (j ForwardedIPPosition) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValueForwardedIPPositions[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j ForwardedIPPosition) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *ForwardedIPPosition) UnmarshalText(text []byte) error {
	result, err := ParseForwardedIPPosition(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j ForwardedIPPosition) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *ForwardedIPPosition) UnmarshalJSON(input []byte) error {
	value := bytes.Trim(input, `"`)

	return j.UnmarshalText(value)
}

// JSONSchema defines a custom definition for JSON schema.
func (ForwardedIPPosition) JSONSchema() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "string",
		Description: "The position of the IP to select if the X-Forwarded-For header has many IPs. Default is rightmost.",
		Enum:        goutils.ToAnySlice(GetForwardedIPPositions()),
		Default:     IPPositionRightmost,
	}
}

// ParseForwardedIPPosition parses a ForwardedIPPosition from string.
func ParseForwardedIPPosition(value string) (ForwardedIPPosition, error) {
	switch value {
	case "rightmost":
		return IPPositionRightmost, nil
	case "leftmost":
		return IPPositionLeftmost, nil
	case "edge":
		return IPPositionEdge, nil
	default:
		return 255, fmt.Errorf(
			"%w, got: %s",
			ErrInvalidForwardedIPLocation,
			value,
		)
	}
}

// GetForwardedIPPositions get the list of forwarded IP position enum.
func GetForwardedIPPositions() []string {
	return enumValueForwardedIPPositions
}

// RelyAuthIPAllowList holds security rules of the IP allow list from the parsed config.
type RelyAuthIPAllowList struct {
	goutils.ValidateIPOptions

	Position ForwardedIPPosition
	Headers  []string
}

// AllowedIPsFromConfig creates a [RelyAuthIPAllowList] instance from config.
func AllowedIPsFromConfig(
	conf *RelyAuthIPAllowListConfig,
	getEnvFunc goenvconf.GetEnvFunc,
) (*RelyAuthIPAllowList, error) {
	if conf == nil ||
		((conf.Include == nil || conf.Include.IsZero()) && (conf.Exclude == nil || conf.Exclude.IsZero())) {
		return nil, ErrEmptyAllowedIPs
	}

	if getEnvFunc == nil {
		getEnvFunc = goenvconf.GetOSEnv
	}

	var headers []string

	if len(conf.Headers) > 0 {
		headers = make([]string, 0, len(conf.Headers))

		for _, header := range conf.Headers {
			if header == "" {
				continue
			}

			headers = append(headers, strings.ToLower(header))
		}

		slices.Sort(headers)
		headers = slices.Compact(headers)
	}

	include, err := parseEnvSubnets(conf.Include, getEnvFunc)
	if err != nil {
		return nil, fmt.Errorf("failed to parse allowed IP: %w", err)
	}

	exclude, err := parseEnvSubnets(conf.Exclude, getEnvFunc)
	if err != nil {
		return nil, fmt.Errorf("failed to parse disallowed IP: %w", err)
	}

	position := conf.Position
	if !conf.Position.IsValid() {
		return nil, ErrInvalidForwardedIPLocation
	}

	result := &RelyAuthIPAllowList{
		ValidateIPOptions: goutils.ValidateIPOptions{
			AllowedIPRanges: include,
			BlockedIPRanges: exclude,
			PublicIPOnly:    conf.PublicOnly,
		},
		Position: position,
		Headers:  headers,
	}

	return result, nil
}

// Validate checks if the request satisfies the security rule.
func (ai *RelyAuthIPAllowList) Validate(body *AuthenticateRequestData) error {
	clientIPs := GetClientIPsFromHeader(body.Headers, ai.Position, ai.Headers...)
	if len(clientIPs) == 0 {
		return ErrIPNotFound
	}

	for _, ip := range clientIPs {
		err := goutils.ValidateIP(ip, ai.ValidateIPOptions)
		if err != nil {
			return err
		}
	}

	return nil
}

func parseEnvSubnets(
	list *goenvconf.EnvStringSlice,
	getEnvFunc goenvconf.GetEnvFunc,
) ([]*net.IPNet, error) {
	if list == nil {
		return nil, nil
	}

	patterns, err := list.GetCustom(getEnvFunc)
	if err != nil {
		return nil, fmt.Errorf("failed to get allowed IP patterns: %w", err)
	}

	if len(patterns) == 0 {
		return nil, nil
	}

	slices.Sort(patterns)

	patterns = slices.Compact(patterns)
	results := make([]*net.IPNet, 0, len(patterns))

	for _, pattern := range patterns {
		trimmed := strings.TrimSpace(pattern)

		if trimmed == "" {
			continue
		}

		ip, err := goutils.ParseSubnet(trimmed)
		if err != nil {
			return nil, err
		}

		results = append(results, ip)
	}

	return results, nil
}
